name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build
      - name: Copy index file to 404 file
        run: cp dist/index.html /dist/404.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: portfolio/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4